root: true
parser: babel-eslint
env:
    browser: true
    node: true
    es6: true
extends:
    - eslint:recommended
    - plugin:import/errors
    - plugin:import/warnings
    - plugin:unicorn/recommended
    - xo/esnext
    - xo/browser
rules:
    dot-location: ["error", "property"]
    wrap-iife: ["error", "any"]
    capitalized-comments: "off"
    indent: ["error", 4]
    max-params: ["warn", 5]
    multiline-ternary: ["error", "always-multiline"]
    new-cap: "off"
    no-console: "error"
    object-curly-spacing: ["error", "always"]
    semi: ["error","never"]
    unicorn/consistent-function-scoping: "off"
    unicorn/explicit-length-check: "off"
    unicorn/import-index: "off"
    unicorn/no-for-loop: "off"
    unicorn/no-unused-properties: "error"
    unicorn/prefer-dataset: "off"
    unicorn/prefer-includes: "off"
    unicorn/prefer-node-append: "off"
    unicorn/prefer-node-remove: "off"
    unicorn/prefer-query-selector: "off"
    unicorn/prefer-text-content: "off"
    unicorn/prevent-abbreviations: "off"
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaVersion: 2018
